//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SP.Resources {
  using System;
  
  
  /// <summary>
  ///   A strongly-typed resource class, for looking up localized strings, etc.
  /// </summary>
  // This class was auto-generated by the StronglyTypedResourceBuilder
  // class via a tool like ResGen or Visual Studio.
  // To add or remove a member, edit your .ResX file then rerun ResGen
  // with the /str option, or rebuild your VS project.
  [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
  [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
  internal class Images {
    
    private static global::System.Resources.ResourceManager resourceMan;
    
    private static global::System.Globalization.CultureInfo resourceCulture;
    
    [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
    internal Images() {
    }
    
    /// <summary>
    ///   Returns the cached ResourceManager instance used by this class.
    /// </summary>
    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    internal static global::System.Resources.ResourceManager ResourceManager {
      get {
        if (object.ReferenceEquals(resourceMan, null)) {
          global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SP.Resources.Images", typeof(Images).Assembly);
          resourceMan = temp;
        }
        return resourceMan;
      }
    }
    
    /// <summary>
    ///   Overrides the current thread's CurrentUICulture property for all
    ///   resource lookups using this strongly typed resource class.
    /// </summary>
    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    internal static global::System.Globalization.CultureInfo Culture {
      get {
        return resourceCulture;
      }
      set {
        resourceCulture = value;
      }
    }
    
    internal static System.Drawing.Bitmap _lock {
      get {
        object obj = ResourceManager.GetObject("lock", resourceCulture);
        return ((System.Drawing.Bitmap)(obj));
      }
    }
    
    internal static System.Drawing.Bitmap account_circle {
      get {
        object obj = ResourceManager.GetObject("account-circle", resourceCulture);
        return ((System.Drawing.Bitmap)(obj));
      }
    }
    
    internal static System.Drawing.Bitmap account_multiple {
      get {
        object obj = ResourceManager.GetObject("account-multiple", resourceCulture);
        return ((System.Drawing.Bitmap)(obj));
      }
    }
    
    internal static System.Drawing.Bitmap account_plus {
      get {
        object obj = ResourceManager.GetObject("account-plus", resourceCulture);
        return ((System.Drawing.Bitmap)(obj));
      }
    }
    
    internal static System.Drawing.Bitmap icons8_bar_chart_24 {
      get {
        object obj = ResourceManager.GetObject("icons8-bar-chart-24", resourceCulture);
        return ((System.Drawing.Bitmap)(obj));
      }
    }
    
    internal static System.Drawing.Bitmap icons8_businessman_24 {
      get {
        object obj = ResourceManager.GetObject("icons8-businessman-24", resourceCulture);
        return ((System.Drawing.Bitmap)(obj));
      }
    }
    
    internal static System.Drawing.Bitmap key {
      get {
        object obj = ResourceManager.GetObject("key", resourceCulture);
        return ((System.Drawing.Bitmap)(obj));
      }
    }
    
    internal static System.Drawing.Bitmap Ripple_1s_200px {
      get {
        object obj = ResourceManager.GetObject("Ripple-1s-200px", resourceCulture);
        return ((System.Drawing.Bitmap)(obj));
      }
    }
  }
}
